# Generated by Django 4.0.3 on 2022-07-06 12:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FacilityInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.TextField(default='')),
                ('fadd', models.DateField(default='')),
                ('ftype', models.TextField(default='')),
            ],
        ),
        migrations.CreateModel(
            name='VaccineInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dsequence', models.TextField(default='')),
                ('dolv', models.DateField(default='')),
                ('brand1', models.TextField(default='')),
                ('brand2', models.TextField(default='')),
                ('brand3', models.TextField(default='')),
            ],
        ),
        migrations.CreateModel(
            name='RegisteredPersons',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wname', models.TextField(default='')),
                ('wnum', models.DateField(default='')),
                ('wtype', models.TextField(default='')),
                ('facility', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testapp.facilityinformation')),
                ('person_info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testapp.personalinformation')),
                ('vaccine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testapp.vaccineinformation')),
            ],
        ),
    ]
