# Generated by Django 4.0.3 on 2022-07-06 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0002_facilityinformation_vaccineinformation_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facilityinformation',
            name='fadd',
            field=models.TextField(default=''),
        ),
    ]
