# Generated by Django 4.0.3 on 2022-07-06 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0003_alter_facilityinformation_fadd'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registeredpersons',
            name='wnum',
            field=models.TextField(default=''),
        ),
    ]
